# .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch: 

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: README Activity Update
        uses: TheDanniCraft/activity-log@v0.0.5
        with:
          GITHUB_USERNAME: "StarrySkyYx"
          GITHUB_TOKEN: ${{ secrets.ACTIONSECRET2024 }} 
