# .github/workflows/update-activity.yml:

name: README Activity Update

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch: 

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update GitHub Activity
        uses: TheDanniCraft/activity-log@v0.0.5
        with:
          GITHUB_USERNAME: "StarrySkyYX"
          GITHUB_TOKEN: ${{ secrets.ACTIONSECRET2024 }} 
